/**
 * Jev slop-meter questions (TypeSafe's jev-1.13 decision model, via OpenRouter)
 *
 * Jev is not a chat model. It gets the post as `state` and returns a
 * probability per typed question, no text. `ai_written` routes the post and is
 * the meter shown on the badge; `author` is only logged, for future tuning.
 *
 * Routing: below JEV_LOW → human, at or above JEV_HIGH → AI, both decided by
 * Jev alone; the band between goes to the Ollama model with the v4.3 prompt.
 *
 * Eval (eval/run-jev.js, 2026-09-18, posts wrapped in LinkedIn chrome like the
 * live feed): 9% of posts reach Ollama; 104/120 AI caught and 4/120 humans
 * flagged, vs gemma alone 105/120 and 12/120. The criteria carry v4.3's
 * false-positive traps; without them false alarms at 90% recall were 13.7%
 * instead of 4.1% (clean text). Cut-offs were fitted on that same data, and
 * LinkedIn chrome shifts the probabilities, so re-check them on the popup's
 * logged scores.
 */

const JEV_LOW = 0.51;
const JEV_HIGH = 0.65;

const JEV_QUESTIONS = {
  ai_written: {
    type: "noul",
    instructions:
      "Ignoring the author's name, headline, and the Like/Comment/Repost buttons and reaction counts around it, was the text of `post` generated by an AI language model rather than written by a person?",
    criteria: {
      true: "Generated by an AI model such as ChatGPT: assistant phrasing or leftover prompt text, 'It's not X. It's Y.' contrasts, a tidy setup-struggle-lesson arc with unnamed characters, generic warm details nobody could check, lessons with no real cost or evidence behind them.",
      false:
        "Written by a person, even if polished or formulaic: company announcements and marketing copy, course or product promotions, one-line-paragraph LinkedIn style, non-native English, highly structured writing, posts with real names, numbers, dates, and opinions that could cost the author something.",
    },
  },
  author: {
    type: "choice",
    instructions: "Who most likely produced the text of `post`?",
    criteria: {
      person: "A person writing in their own voice about their work, life, or opinions",
      company: "A company, brand, or marketing team writing a polished announcement or promotion",
      ai: "An AI language model such as ChatGPT generating the post from a prompt",
    },
  },
};

// Browser (content script, popup) or Node (eval harness)
if (typeof window !== "undefined") Object.assign(window, { JEV_QUESTIONS, JEV_LOW, JEV_HIGH });
if (typeof module !== "undefined") module.exports = { JEV_QUESTIONS, JEV_LOW, JEV_HIGH };
